name: CI Build & Test
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      # - name: Install D2 For Docs
      #   run: curl -fsSL https://d2lang.com/install.sh | sh -s --
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.22
      - name: Init Environment Variables
        env:
          PB_URL: ${{ secrets.PB_URL }}
          PB_ADMIN_USERNAME: ${{ secrets.PB_ADMIN_USERNAME }}
          PB_ADMIN_PASSWORD: ${{ secrets.PB_ADMIN_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bun scripts/init-env-vars.ts
      - name: Install Dependencies
        run: pnpm i
      - name: Build and Test
        run: |
          pnpm build
          pnpm test
      # - name: Update Data
      #   run: pnpm scrape
